### PR TITLE
add active tag

### LINKED ISSUE #184: make sure queries check Active flag

### PR DESCRIPTION
**Pull request by laholstege**
closes #184

### CODE REVIEW

**Comment by jcubbage** [comment]
Should this be a flag on the react components? How do we pull up inactive items (in case we need to reactivate). Also, we need some way of setting this flag (although I can be convinced that's a separate issue/PR).

**Comment by laholstege** [comment]
@jcubbage i think react will only deal with active items, except maybe to de-activate/remove assets. we would have some static page for reactivating. what do you think, @srkirkland ?

**Comment by srkirkland** [comment]
@laholstege @jcubbage yea we'll just have an inactive report somewhere.  I'm not sure we should ever re-activate an old thing except maybe people.

**Comment by srkirkland** [comment]
@laholstege something to think about -- we can set the class mapping so that isActive is automatically applied at the model level, then you don't have to add it in to each query.

**Comment by srkirkland** [comment]
@laholstege that would be like https://docs.microsoft.com/en-us/ef/core/querying/filters

**Pull request closed without merging**
