### PR TITLE
Design2

### PR DESCRIPTION
**Pull request by cydoval**
HECKIN COOL STUFF

### CODE REVIEW

**Comment by jcubbage** [comment]
I don't know....looks the same to me. :)

**Comment by jcubbage** [comment]
@cydoval Can you look at the non-react pages? This update made the fonts on those pages tiny. I think that's bootstrap's weird font setting for tables at work.
Example: http://localhost:5000/CAESDO/Confirm/Confirm
http://localhost:5000/CAESDO/TeamAdmin/Members
http://localhost:5000/CAESDO/TeamAdmin/RoledMembers
http://localhost:5000/CAESDO/TagsManager

**Comment by cydoval** [comment]
@jcubbage I'm going to delete this PR, laura put in master into this branch, I will address those things you linked in the fututure though

**Comment by cydoval** [comment]
@jcubbage ill work on those changes

**Comment by cydoval** [comment]
@jcubbage can you take a look now? the tables should be fixed. I have a lot more styling work in general to but taht will be for later PRs

**Comment by jcubbage** [comment]
So much better! Thanks Cal!

**Pull request merged**
