### PR TITLE
Jcs/more tracks

### PR DESCRIPTION
**Pull request by jSylvestre**
image

### CODE REVIEW

**Comment by jSylvestre** [comment]
I'm using the key title, want me to use the key code instead?

**Comment by jSylvestre** [comment]
> in the future our services shouldn't be doing _dbContext.SaveChanges(). The calling code should be responsive for triggering save (or not). The way it currently is isn't the best for performance or ability to rollback in case of errors.

That is something for future @jcubbage :)

**Comment by jcubbage** [comment]
> I'm using the key title, want me to use the key code instead?

I think we should always be using asset.Title. For keys that returns name if available, code if not. KeySerials get name then number. For KeySerial we may want to extend further with FullName => {key.Title}-{keyserial.Title}?

**Comment by jcubbage** [comment]
> in the future our services shouldn't be doing _dbContext.SaveChanges(). The calling code should be responsive for triggering save (or not). The way it currently is isn't the best for performance or ability to rollback in case of errors.

Does that mean our controllers should be saving changes twice? We need the full object in the event service, so do we start doing this:

await _context.SaveChangesAsync();
await _eventService.TrackAssignAccess(accessAssignment, Team);
await _context.SaveChangesAsync();

**Comment by srkirkland** [comment]
@jcubbage I don't know enough about the specific problems but I would think anything you need in the event service you already have without saving.

**Comment by jcubbage** [comment]
> @jcubbage I don't know enough about the specific problems but I would think anything you need in the event service you already have without saving.

@srkirkland You were right. I thought the object had to be saved before calling the eventService...but I was mistaken.
Did new PR with all the saveChanges pulled from history & notification services. Can either merge with this, or review/approve separate.

**Pull request merged**
